"""remove_user_token

Revision ID: 328ba6da17c0
Revises: b4821735eca0
Create Date: 2022-05-26 18:09:39.980356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328ba6da17c0'
down_revision = 'b4821735eca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Push notification token'))
    # ### end Alembic commands ###
