"""pair_created_by_user_id

Revision ID: 3be812f4fff7
Revises: d3042e6a7674
Create Date: 2022-05-19 17:58:57.301058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be812f4fff7'
down_revision = 'd3042e6a7674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pair', sa.Column('created_by_user_id', sa.Integer(), nullable=True, comment='Who has created the pair'))
    op.create_foreign_key(None, 'pair', 'user', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pair', type_='foreignkey')
    op.drop_column('pair', 'created_by_user_id')
    # ### end Alembic commands ###
