"""visit_score

Revision ID: 5bab531b457a
Revises: e455d34da812
Create Date: 2022-05-22 20:03:01.685579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bab531b457a'
down_revision = 'e455d34da812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('score', sa.Float(), nullable=True, comment='Score'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'score')
    # ### end Alembic commands ###
