"""cascade

Revision ID: 793250905e86
Revises: c55bfc758db7
Create Date: 2022-05-27 14:06:38.765835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793250905e86'
down_revision = 'c55bfc758db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pair_created_by_user_id_fkey', 'pair', type_='foreignkey')
    op.create_foreign_key(None, 'pair', 'user', ['created_by_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pair', type_='foreignkey')
    op.create_foreign_key('pair_created_by_user_id_fkey', 'pair', 'user', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###
