"""visit_pair_id

Revision ID: 8fe96b4c4463
Revises: 62c8d6bae11c
Create Date: 2022-05-19 15:58:15.173704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe96b4c4463'
down_revision = '62c8d6bae11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('pair_id', sa.Integer(), nullable=True, comment='Pair'))
    op.alter_column('visit', 'user_id',
               existing_type=sa.INTEGER(),
               comment='User',
               existing_nullable=True)
    op.create_foreign_key(None, 'visit', 'pair', ['pair_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.alter_column('visit', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User',
               existing_nullable=True)
    op.drop_column('visit', 'pair_id')
    # ### end Alembic commands ###
