"""permissions

Revision ID: 984fb8c198d0
Revises: 8fe96b4c4463
Create Date: 2022-05-19 16:11:35.885177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984fb8c198d0'
down_revision = '8fe96b4c4463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=250), nullable=True, comment='Scope to allow'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=True, comment='Permission'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='Role'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
