"""pair_scores

Revision ID: b4821735eca0
Revises: ceeaedd3cb1a
Create Date: 2022-05-24 16:35:18.404832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4821735eca0'
down_revision = 'ceeaedd3cb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pair', sa.Column('visit_score', sa.Float(), nullable=True, comment='Score for each pair visit'))
    op.add_column('pair', sa.Column('missed_score', sa.Float(), nullable=True, comment='Score for each pair miss'))
    op.add_column('pair', sa.Column('sick_score', sa.Float(), nullable=True, comment='Score when user were sick'))
    op.drop_column('visit', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Score'))
    op.drop_column('pair', 'sick_score')
    op.drop_column('pair', 'missed_score')
    op.drop_column('pair', 'visit_score')
    # ### end Alembic commands ###
