"""cascade

Revision ID: c55bfc758db7
Revises: 328ba6da17c0
Create Date: 2022-05-27 13:59:27.697977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55bfc758db7'
down_revision = '328ba6da17c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_permission_permission_id_fkey', 'role_permission', type_='foreignkey')
    op.drop_constraint('role_permission_role_id_fkey', 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permission', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key('role_permission_role_id_fkey', 'role_permission', 'role', ['role_id'], ['id'])
    op.create_foreign_key('role_permission_permission_id_fkey', 'role_permission', 'permission', ['permission_id'], ['id'])
    # ### end Alembic commands ###
