"""pair_room

Revision ID: d3042e6a7674
Revises: 984fb8c198d0
Create Date: 2022-05-19 17:56:17.848069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3042e6a7674'
down_revision = '984fb8c198d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pair', sa.Column('room', sa.String(length=250), nullable=True, comment='Room'))
    op.add_column('pair', sa.Column('start_at', sa.Time(), nullable=True, comment='When the pair starts'))
    op.add_column('pair', sa.Column('end_at', sa.Time(), nullable=True, comment='When the pair ends'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pair', 'end_at')
    op.drop_column('pair', 'start_at')
    op.drop_column('pair', 'room')
    # ### end Alembic commands ###
