"""cascade

Revision ID: d53bf848870b
Revises: 5bab531b457a
Create Date: 2022-05-23 17:41:08.841206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53bf848870b'
down_revision = '5bab531b457a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_pair_pair_id_fkey', 'user_pair', type_='foreignkey')
    op.drop_constraint('user_pair_user_id_fkey', 'user_pair', type_='foreignkey')
    op.create_foreign_key(None, 'user_pair', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_pair', 'pair', ['pair_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('visit_user_id_fkey', 'visit', type_='foreignkey')
    op.drop_constraint('visit_pair_id_fkey', 'visit', type_='foreignkey')
    op.create_foreign_key(None, 'visit', 'pair', ['pair_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'visit', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.create_foreign_key('visit_pair_id_fkey', 'visit', 'pair', ['pair_id'], ['id'])
    op.create_foreign_key('visit_user_id_fkey', 'visit', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_pair', type_='foreignkey')
    op.drop_constraint(None, 'user_pair', type_='foreignkey')
    op.create_foreign_key('user_pair_user_id_fkey', 'user_pair', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_pair_pair_id_fkey', 'user_pair', 'pair', ['pair_id'], ['id'])
    # ### end Alembic commands ###
