"""user_pair

Revision ID: f5726465945d
Revises: 3be812f4fff7
Create Date: 2022-05-19 18:15:07.601304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5726465945d'
down_revision = '3be812f4fff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pair',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User'),
    sa.Column('pair_id', sa.Integer(), nullable=True, comment='Pair'),
    sa.ForeignKeyConstraint(['pair_id'], ['pair.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pair')
    # ### end Alembic commands ###
